import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f0f2f5' },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
  },
  headerButtons: { flexDirection: 'row', alignItems: 'center'},
  sizeLabel: { marginLeft: 10, fontSize: 14, color: '#333', textAlign: 'right', width: 70},
  clearButton: { marginRight: 12, padding: 4 },
  refreshButton: { marginLeft: 12, padding: 4 },
  editButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f0f0f0',
    marginRight: 8,
  },
  editButtonActive: { backgroundColor: '#007AFF' },
  addButton: {
    backgroundColor: '#007AFF',
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  addButtonActive: { backgroundColor: '#34c759' },
  sizeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 12,
  },
  sizeInput: {
    width: 50,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d1d5db',
    color: '#111',
    backgroundColor: '#fff',
    marginRight: 8,
    textAlign: 'center'
  },
  sizeSaveButton: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#007AFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sizeSaveButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  bgButton: {
    marginLeft: 10,
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d1d5db',
  },
  mapContainer: { flex: 1, backgroundColor: '#e9ecef', position: 'relative' },
  tableContainer: { position: 'absolute', left: 0, top: 0 },
  table: {
    backgroundColor: '#4cd964',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 2,
    borderColor: '#fff',
  },
  tableOccupied: { backgroundColor: '#ff9500' },
  tableReady: { backgroundColor: '#ff69b4' },
  tableSelected: { borderWidth: 4, borderColor: '#007AFF' },
  tableNumber: { fontSize: 20, fontWeight: 'bold', color: '#fff' },
  tableStatus: { fontSize: 10, color: '#fff', marginTop: 4 },
  orderButtonContainer: {
    position: 'absolute',
    bottom: 30,
    left: 20,
    right: 20,
    alignItems: 'center',
  },
  orderButton: {
    flexDirection: 'row',
    backgroundColor: '#007AFF',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  orderButtonText: { color: '#fff', fontSize: 18, fontWeight: '600', marginLeft: 8 },
  helperTextContainer: {
    position: 'absolute',
    bottom: 100,
    left: 20,
    right: 20,
    alignItems: 'center',
  },
  helperText: {
    backgroundColor: 'rgba(0,0,0,0.7)',
    color: '#fff',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    fontSize: 14,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
  },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 },
  modalTitle: { fontSize: 20, fontWeight: 'bold' },
  orderDetails: { marginBottom: 12 },
  detailRow: { marginBottom: 6, fontSize: 14 },
  detailLabel: { fontWeight: '600', color: '#666' },
  platesTitle: { fontSize: 18, fontWeight: '600', marginTop: 8, marginBottom: 8 },
  plateItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  plateInfo: { flex: 1 },
  plateName: { fontSize: 16 },
  plateComment: { fontSize: 13, color: '#888', fontStyle: 'italic' },
  platePrice: { fontSize: 14, fontWeight: '500', marginRight: 10 },
  plateStatus: { fontSize: 14, color: '#007AFF' },
  mapWrapper: {
    flex: 1,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapTransformContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default styles;